[build]
builder = "NIXPACKS"

[deploy]
startCommand = ". /opt/venv/bin/activate && python run.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ENVIRONMENT = "production"
